let db=null;
async function initDb(){try{const t=await fetch('./index.html',{cache:'no-store'}).then(r=>r.text()),u=t.match(/const URL='([^']+)'/),k=t.match(/KEY='([^']+)'/);if(u&&k&&window.supabase)db=window.supabase.createClient(u[1],k[1])}catch(e){db=null}}
const STORE='asm70_live_stats_v2',ROSTER_STORE='asm70_live_roster_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let online={settings:null,players:[],games:[],callups:[]};
let localRoster=[],draftOpp=[];
let S=null,selectedPlayer=null,selectedSide='us',clockTimer=null,savePulse=0;
const actionDefs=[
  ['1M','✓ 1 punto','good'],['2M','✓ 2 punti','good'],['3M','✓ 3 punti','good'],
  ['1X','✕ TL','miss'],['2X','✕ 2 punti','miss'],['3X','✕ 3 punti','miss'],
  ['RD','Rimb. dif.','orange'],['RO','Rimb. off.','orange'],['AST','Assist','blue'],['STL','Recupero','blue'],['TO','Palla persa','red'],['BLK','Stoppata','blue'],
  ['FOUL','Fallo','red'],['FREC','Fallo subito','orange'],['SUB','Cambio','change']
];
const pointsByType={'1M':1,'2M':2,'3M':3};
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmt(sec){sec=Math.max(0,Math.round(sec||0));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.add('hidden'),1400)}
function save(){if(S)localStorage.setItem(STORE,JSON.stringify(S))}
function saveRoster(){localStorage.setItem(ROSTER_STORE,JSON.stringify(localRoster))}
function sideOf(e){return e.side||'us'}
function stat(side,pid,type,period=null){return S.events.filter(e=>sideOf(e)===side&&e.playerId===pid&&e.type===type&&(period===null||e.period===period)).length}
function madePts(side,pid=null){return S.events.reduce((a,e)=>a+(sideOf(e)===side&&(pid===null||e.playerId===pid)?(pointsByType[e.type]||0):0),0)}
function teamFouls(side){return S.events.filter(e=>sideOf(e)===side&&e.type==='FOUL'&&e.period===S.period).length}
function ratio(side,pid,x){let a=stat(side,pid,x+'M'),b=stat(side,pid,x+'X');return a+'/'+(a+b)}
function findPlayer(side,id){return (side==='us'?S.players:S.opponents).find(p=>p.id===id)}
function newState(players,opponents){let len=Number($('#periodLen').value)||600;return{version:2,createdAt:new Date().toISOString(),team:$('#teamInput').value.trim()||'ASM70 U14',opponent:$('#oppInput').value.trim()||'Avversari',homeAway:$('#homeAway').value,gameId:$('#gameSelect').value||null,periodLen:len,period:1,clock:len,running:false,players:players.map((p,i)=>({id:p.id||uid(),name:p.name,num:Number(p.num)||0,onCourt:i<5,sec:0})),opponents:opponents.map(p=>({id:p.id||'opp_'+uid(),name:p.name||'',num:Number(p.num)||0})),events:[]}}
function normalizeState(){if(!S)return;if(!Array.isArray(S.opponents))S.opponents=[];if(!Array.isArray(S.events))S.events=[];S.version=2;S.events.forEach(e=>{if(!e.side)e.side='us'});S.players.forEach(p=>{if(typeof p.sec!=='number')p.sec=0;if(typeof p.onCourt!=='boolean')p.onCourt=false})}
async function loadOnline(){try{if(!db)await initDb();if(!db)throw Error('offline');let s=await db.from('team_settings').select('*').eq('id',1).single();if(s.data){online.settings=s.data;$('#teamInput').value=s.data.team_name||'ASM70 U14'}let [p,g,c]=await Promise.all([db.from('players').select('*').eq('active',true).order('display_order').order('jersey_number'),db.from('games').select('*').order('game_date',{ascending:false}).limit(40),db.from('game_callups').select('*')]);online.players=p.data||[];online.games=g.data||[];online.callups=c.data||[];$('#loadStatus').textContent='roster online caricato'}catch(e){$('#loadStatus').textContent='offline · uso roster locale'}mergeRoster();renderGameOptions();renderRosterSetup();renderOppDraft()}
function mergeRoster(){let saved=[];try{saved=JSON.parse(localStorage.getItem(ROSTER_STORE)||'[]')}catch(e){}let map=new Map();online.players.forEach(p=>map.set(String(p.id),{id:String(p.id),name:p.name,num:p.jersey_number||0,selected:true}));saved.forEach(p=>{if(!map.has(String(p.id)))map.set(String(p.id),p)});localRoster=[...map.values()].sort((a,b)=>(a.num||999)-(b.num||999)||a.name.localeCompare(b.name))}
function renderGameOptions(){let sel=$('#gameSelect'),cur=sel.value;sel.innerHTML='<option value="">Partita manuale</option>';online.games.forEach(g=>{let o=document.createElement('option');o.value=g.id;o.textContent=`${g.game_date} · ${g.home_away==='home'?'vs':'@'} ${g.opponent}`;sel.appendChild(o)});if([...sel.options].some(o=>o.value===cur))sel.value=cur}
function renderRosterSetup(){let box=$('#rosterGrid');if(!localRoster.length){box.innerHTML='<div style="grid-column:1/-1;padding:18px;text-align:center;color:#7a8798">Nessun giocatore: aggiungilo qui sotto oppure dall’admin U14.</div>';return}box.innerHTML=localRoster.map((p,i)=>`<label class="rosterPick ${p.selected===false?'off':''}"><input type="checkbox" data-ridx="${i}" ${p.selected===false?'':'checked'}><span class="rnum">${esc(p.num)}</span><span class="rname">${esc(p.name)}</span></label>`).join('');$$('[data-ridx]').forEach(ch=>ch.onchange=()=>{localRoster[+ch.dataset.ridx].selected=ch.checked;saveRoster();renderRosterSetup()})}
function renderOppDraft(){let box=$('#oppRosterPreview');if(!draftOpp.length){box.innerHTML='<span class="oppHint">Inserisci i numeri della squadra avversaria. Non vengono salvati nel roster U14.</span>';return}box.innerHTML=draftOpp.map((p,i)=>`<button class="oppChip" data-od="${i}">#${esc(p.num)} <span>×</span></button>`).join('');$$('[data-od]').forEach(b=>b.onclick=()=>{draftOpp.splice(+b.dataset.od,1);renderOppDraft()})}
function parseOppNumbers(){let raw=$('#oppNumbers').value.trim();if(!raw)return toast('Inserisci almeno un numero');let nums=[...new Set(raw.split(/[\s,;/-]+/).map(x=>parseInt(x,10)).filter(n=>Number.isFinite(n)&&n>=0&&n<=99))];if(!nums.length)return toast('Numeri non validi');draftOpp=nums.sort((a,b)=>a-b).map(n=>({id:'opp_'+uid(),num:n,name:''}));renderOppDraft();toast(`${nums.length} numeri avversari caricati`)}
$('#buildOpp').onclick=parseOppNumbers;
$('#gameSelect').onchange=()=>{let id=$('#gameSelect').value,g=online.games.find(x=>x.id===id);if(!g)return;if(g.opponent)$('#oppInput').value=g.opponent;if(g.home_away)$('#homeAway').value=g.home_away;let ids=online.callups.filter(c=>c.game_id===id).map(c=>String(c.player_id));if(ids.length){localRoster.forEach(p=>p.selected=ids.includes(String(p.id)));saveRoster();renderRosterSetup()}draftOpp=[];$('#oppNumbers').value='';renderOppDraft()};
$('#addPlayer').onclick=()=>{let num=Number($('#newNum').value),name=$('#newName').value.trim();if(!name)return toast('Inserisci il nome');localRoster.push({id:'local_'+uid(),name,num:num||0,selected:true});localRoster.sort((a,b)=>(a.num||999)-(b.num||999)||a.name.localeCompare(b.name));saveRoster();$('#newNum').value='';$('#newName').value='';renderRosterSetup()};
function showGame(){stopClock();$('#setupView').classList.add('hidden');$('#gameView').classList.remove('hidden');renderAll()}
function showSetup(){stopClock();save();$('#gameView').classList.add('hidden');$('#setupView').classList.remove('hidden');$('#resumeBtn').classList.toggle('hidden',!S)}
$('#startBtn').onclick=()=>{let chosen=localRoster.filter(p=>p.selected!==false);if(chosen.length<1)return toast('Seleziona almeno un giocatore');if(!draftOpp.length&&$('#oppNumbers').value.trim())parseOppNumbers();S=newState(chosen,draftOpp);save();showGame()};
$('#resumeBtn').onclick=()=>{if(S)showGame()};
$('#setupBack').onclick=showSetup;
$('#newGame').onclick=()=>{if(confirm('Vuoi chiudere questa partita e crearne una nuova?')){stopClock();localStorage.removeItem(STORE);S=null;draftOpp=[];$('#oppNumbers').value='';renderOppDraft();showSetup()}};
function renderAll(){if(!S)return;normalizeState();$('#teamNameTop').textContent=S.team;$('#oppNameTop').textContent=S.opponent;$('#ourScore').textContent=madePts('us');$('#oppScore').textContent=madePts('opp');$('#periodBtn').textContent='Q'+S.period;$('#clock').textContent=fmt(S.clock);$('#clockBtn').textContent=S.running?'❚❚':'▶';$('#teamFouls').textContent=`Falli ${S.team} Q${S.period}: ${teamFouls('us')}`;$('#oppFouls').textContent=`Falli ${S.opponent} Q${S.period}: ${teamFouls('opp')}`;renderPlayers();renderOpponents();renderEvents();renderStats()}
function playerCard(p,isCourt){let fouls=stat('us',p.id,'FOUL'),pts=madePts('us',p.id);return `<button class="player ${isCourt?'five':'out'} ${fouls>=5?'fouledout':''}" data-pid="${esc(p.id)}"><div><div class="num">${esc(p.num)}</div><div class="pname">${esc(p.name)}</div></div><div class="pmeta"><div class="ppts">${pts} pt</div><div class="fouls">${[0,1,2,3,4].map(i=>`<i class="${i<fouls?'on':''}"></i>`).join('')}</div></div></button>`}
function renderPlayers(){let court=$('#courtPlayers'),bench=$('#benchPlayers');let on=S.players.filter(p=>p.onCourt),off=S.players.filter(p=>!p.onCourt);court.innerHTML=on.map(p=>playerCard(p,true)).join('')||'<div class="empty" style="grid-column:1/-1">Nessun giocatore in campo.</div>';bench.innerHTML=off.map(p=>playerCard(p,false)).join('')||'<div class="empty" style="padding:12px">Panchina vuota</div>';$$('[data-pid]').forEach(b=>b.onclick=()=>openActions('us',b.dataset.pid))}
function renderOpponents(){let box=$('#oppPlayers');if(!S.opponents.length){box.innerHTML='<div class="empty">Nessun numero avversario. Puoi aggiungerlo con “+ numero”.</div>';return}box.innerHTML=S.opponents.map(p=>{let f=stat('opp',p.id,'FOUL'),pts=madePts('opp',p.id);return `<button class="oppPlayer ${f>=5?'fouledout':''}" data-oppid="${esc(p.id)}"><div class="oppNum">${esc(p.num)}</div><div class="oppMeta"><span>${pts} pt</span><span>${f} F</span></div></button>`}).join('');$$('[data-oppid]').forEach(b=>b.onclick=()=>openActions('opp',b.dataset.oppid))}
$('#addOppInGame').onclick=()=>{if(!S)return;let raw=prompt('Numero maglia avversario da aggiungere:');let n=parseInt(raw,10);if(!Number.isFinite(n)||n<0||n>99)return;if(S.opponents.some(p=>p.num===n))return toast('Numero già presente');S.opponents.push({id:'opp_'+uid(),num:n,name:''});S.opponents.sort((a,b)=>a.num-b.num);save();renderAll();toast(`Aggiunto #${n}`)};
function historyRows(){let us=0,opp=0;return S.events.map(e=>{let pts=pointsByType[e.type]||0;if(sideOf(e)==='us')us+=pts;else opp+=pts;return{...e,scoreUs:us,scoreOpp:opp}})}
function renderEvents(){let box=$('#eventList');if(!S.events.length){box.innerHTML='<div class="empty">La cronologia si costruisce automaticamente: Q, tempo, squadra, numero, azione e punteggio.</div>';return}let labels=Object.fromEntries(actionDefs.map(x=>[x[0],x[1]]));box.innerHTML=historyRows().reverse().slice(0,250).map(e=>{let side=sideOf(e),p=e.playerId?findPlayer(side,e.playerId):null,team=side==='us'?S.team:S.opponent;return `<div class="event ${side==='opp'?'oppEvent':'usEvent'}"><div class="etime">Q${e.period} ${fmt(e.clock)}</div><div class="eventTeam">${esc(team)}</div><div class="enum">${p?'#'+esc(p.num):'#?'}</div><div class="elabel">${p&&p.name?esc(p.name)+' · ':''}${esc(labels[e.type]||e.label||e.type)}</div><div class="eventScore">${e.scoreUs}-${e.scoreOpp}</div></div>`}).join('')}
function renderStats(){if(!S)return;$('#statsScore').textContent=`${S.team} ${madePts('us')} – ${madePts('opp')} ${S.opponent}`;$('#statsBody').innerHTML=S.players.map(p=>{let rd=stat('us',p.id,'RD'),ro=stat('us',p.id,'RO');return `<tr><td><div class="statsName"><span class="smallNum">${esc(p.num)}</span>${esc(p.name)}</div></td><td>${fmt(p.sec)}</td><td><b>${madePts('us',p.id)}</b></td><td>${ratio('us',p.id,'1')}</td><td>${ratio('us',p.id,'2')}</td><td>${ratio('us',p.id,'3')}</td><td>${rd}</td><td>${ro}</td><td><b>${rd+ro}</b></td><td>${stat('us',p.id,'AST')}</td><td>${stat('us',p.id,'STL')}</td><td>${stat('us',p.id,'TO')}</td><td>${stat('us',p.id,'BLK')}</td><td>${stat('us',p.id,'FOUL')}</td><td>${stat('us',p.id,'FREC')}</td></tr>`}).join('');$('#oppStatsBody').innerHTML=S.opponents.map(p=>`<tr><td><div class="statsName"><span class="smallNum oppSmall">${esc(p.num)}</span>${esc(p.name||'Avversario')}</div></td><td><b>${madePts('opp',p.id)}</b></td><td>${ratio('opp',p.id,'1')}</td><td>${ratio('opp',p.id,'2')}</td><td>${ratio('opp',p.id,'3')}</td><td>${stat('opp',p.id,'RD')+stat('opp',p.id,'RO')}</td><td>${stat('opp',p.id,'AST')}</td><td>${stat('opp',p.id,'STL')}</td><td>${stat('opp',p.id,'TO')}</td><td>${stat('opp',p.id,'BLK')}</td><td>${stat('opp',p.id,'FOUL')}</td></tr>`).join('')||'<tr><td colspan="11">Nessun numero avversario inserito.</td></tr>'}
function openActions(side,pid){selectedSide=side;selectedPlayer=pid;let p=findPlayer(side,pid);if(!p)return;$('#sheetNum').textContent=p.num;$('#sheetName').textContent=side==='us'?(p.name||'Giocatore'):`${S.opponent} · #${p.num}`;$('#sheetMini').textContent=side==='us'?`${madePts(side,pid)} punti · ${stat(side,pid,'FOUL')} falli · ${fmt(p.sec)} in campo`:`${madePts(side,pid)} punti · ${stat(side,pid,'FOUL')} falli`;let defs=side==='us'?actionDefs:actionDefs.filter(a=>a[0]!=='SUB');$('#actions').innerHTML=defs.map(a=>`<button class="act ${a[2]}" data-act="${a[0]}">${a[1]}</button>`).join('');$$('[data-act]').forEach(b=>b.onclick=()=>doAction(b.dataset.act));$('#actionBack').classList.remove('hidden')}
function closeActions(){$('#actionBack').classList.add('hidden')}
$('#closeSheet').onclick=closeActions;$('#actionBack').onclick=e=>{if(e.target===$('#actionBack'))closeActions()};
function doAction(type){if(type==='SUB'&&selectedSide==='us'){closeActions();return openSubs()}let p=findPlayer(selectedSide,selectedPlayer);if(!p)return;S.events.push({id:uid(),side:selectedSide,playerId:p.id,type,period:S.period,clock:S.clock,at:new Date().toISOString()});save();closeActions();renderAll();toast(`${selectedSide==='opp'?S.opponent:S.team} #${p.num} · ${actionDefs.find(a=>a[0]===type)?.[1]||type}`)}
function openSubs(){let p=findPlayer('us',selectedPlayer);if(!p)return;let candidates=S.players.filter(x=>x.id!==p.id&&x.onCourt!==p.onCourt);$('#subTitle').textContent=p.onCourt?`Chi entra al posto di #${p.num} ${p.name}?`:`Chi esce per far entrare #${p.num} ${p.name}?`;$('#subGrid').innerHTML=candidates.length?candidates.map(x=>`<button class="subPick" data-sub="${esc(x.id)}">#${esc(x.num)} · ${esc(x.name)}</button>`).join(''):'<div class="empty" style="grid-column:1/-1">Nessun cambio disponibile.</div>';$$('[data-sub]').forEach(b=>b.onclick=()=>swapPlayers(p.id,b.dataset.sub));$('#subBack').classList.remove('hidden')}
function swapPlayers(a,b){let p=findPlayer('us',a),q=findPlayer('us',b);if(!p||!q)return;let x=p.onCourt;p.onCourt=q.onCourt;q.onCourt=x;S.events.push({id:uid(),side:'us',playerId:p.id,otherPlayerId:q.id,type:'SUB',label:`Cambio ${p.onCourt?'entra':'esce'} con #${q.num} ${q.name}`,period:S.period,clock:S.clock,at:new Date().toISOString()});save();$('#subBack').classList.add('hidden');renderAll();toast('Cambio registrato')}
$('#closeSub').onclick=()=>$('#subBack').classList.add('hidden');$('#subBack').onclick=e=>{if(e.target===$('#subBack'))$('#subBack').classList.add('hidden')};
function stopClock(){if(clockTimer){clearInterval(clockTimer);clockTimer=null}if(S)S.running=false}
function startClock(){if(!S||S.clock<=0||clockTimer)return;S.running=true;clockTimer=setInterval(()=>{if(!S||!S.running)return;S.clock=Math.max(0,S.clock-1);S.players.filter(p=>p.onCourt).forEach(p=>p.sec=(p.sec||0)+1);savePulse++;if(savePulse%5===0)save();if(S.clock===0){stopClock();save()}renderAll()},1000);renderAll()}
$('#clockBtn').onclick=()=>{if(!S)return;if(S.running){stopClock();save();renderAll()}else startClock()};
$('#periodBtn').onclick=()=>{if(!S)return;stopClock();let n=S.period>=4?1:S.period+1;if(confirm(`Passare a Q${n} e reimpostare il cronometro a ${fmt(S.periodLen)}?`)){S.period=n;S.clock=S.periodLen;save();renderAll()}};
$$('[data-opp-unknown]').forEach(b=>b.onclick=()=>{if(!S)return;let type=b.dataset.oppUnknown+'M';S.events.push({id:uid(),side:'opp',playerId:null,type,label:`${b.dataset.oppUnknown} punto${b.dataset.oppUnknown==='1'?'':'i'} · numero non rilevato`,period:S.period,clock:S.clock,at:new Date().toISOString()});save();renderAll();toast(`Avversari +${b.dataset.oppUnknown}`)});
function undo(){if(!S||!S.events.length)return toast('Nulla da annullare');let e=S.events.pop();if(e.type==='SUB'&&e.otherPlayerId){let a=findPlayer('us',e.playerId),b=findPlayer('us',e.otherPlayerId);if(a&&b){let x=a.onCourt;a.onCourt=b.onCourt;b.onCourt=x}}toast('Ultima azione annullata');save();renderAll()}
$('#quickUndo').onclick=undo;$('#historyUndo').onclick=undo;
$('#clearEvents').onclick=()=>{if(confirm('Azzero tutta la cronologia? Anche i punteggi torneranno a 0.')){S.events=[];save();renderAll()}};
$$('.nav [data-tab]').forEach(b=>b.onclick=()=>{$$('.nav [data-tab]').forEach(x=>x.classList.toggle('on',x===b));['live','history','stats'].forEach(t=>$('#tab'+t[0].toUpperCase()+t.slice(1)).classList.toggle('hidden',b.dataset.tab!==t));if(b.dataset.tab==='history')renderEvents();if(b.dataset.tab==='stats')renderStats()});
$('#exportCsv').onclick=()=>{if(!S)return;let rows=[['Squadra','Numero','Giocatore','Min','Punti','TL','2PT','3PT','RD','RO','RT','Assist','Recuperi','Perse','Stoppate','Falli','Falli subiti']];S.players.forEach(p=>{let rd=stat('us',p.id,'RD'),ro=stat('us',p.id,'RO');rows.push([S.team,p.num,p.name,fmt(p.sec),madePts('us',p.id),ratio('us',p.id,'1'),ratio('us',p.id,'2'),ratio('us',p.id,'3'),rd,ro,rd+ro,stat('us',p.id,'AST'),stat('us',p.id,'STL'),stat('us',p.id,'TO'),stat('us',p.id,'BLK'),stat('us',p.id,'FOUL'),stat('us',p.id,'FREC')])});S.opponents.forEach(p=>{let rd=stat('opp',p.id,'RD'),ro=stat('opp',p.id,'RO');rows.push([S.opponent,p.num,p.name||'','',madePts('opp',p.id),ratio('opp',p.id,'1'),ratio('opp',p.id,'2'),ratio('opp',p.id,'3'),rd,ro,rd+ro,stat('opp',p.id,'AST'),stat('opp',p.id,'STL'),stat('opp',p.id,'TO'),stat('opp',p.id,'BLK'),stat('opp',p.id,'FOUL'),stat('opp',p.id,'FREC')])});let csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');let blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`stats_${S.opponent.replace(/[^a-z0-9]+/gi,'_')}_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#exportHistory').onclick=()=>{if(!S)return;let labels=Object.fromEntries(actionDefs.map(x=>[x[0],x[1]]));let rows=[['Quarto','Tempo','Squadra','Numero','Giocatore','Azione','Punteggio']];historyRows().forEach(e=>{let side=sideOf(e),p=e.playerId?findPlayer(side,e.playerId):null;rows.push(['Q'+e.period,fmt(e.clock),side==='us'?S.team:S.opponent,p?.num??'?',p?.name||'',labels[e.type]||e.label||e.type,`${e.scoreUs}-${e.scoreOpp}`])});let csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');let blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cronologia_${S.opponent.replace(/[^a-z0-9]+/gi,'_')}_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.addEventListener('beforeunload',save);
(function init(){try{S=JSON.parse(localStorage.getItem(STORE)||'null')}catch(e){S=null}if(S){S.running=false;normalizeState()}$('#resumeBtn').classList.toggle('hidden',!S);loadOnline();if(S){$('#teamInput').value=S.team||'ASM70 U14';$('#oppInput').value=S.opponent||'';$('#homeAway').value=S.homeAway||'home';$('#periodLen').value=String(S.periodLen||600);draftOpp=S.opponents.map(p=>({...p}));$('#oppNumbers').value=draftOpp.map(p=>p.num).join(', ');renderOppDraft()}})();
