let db=null;
async function initDb(){try{const t=await fetch('./index.html',{cache:'no-store'}).then(r=>r.text()),u=t.match(/const URL='([^']+)'/),k=t.match(/KEY='([^']+)'/);if(u&&k&&window.supabase)db=window.supabase.createClient(u[1],k[1])}catch(e){db=null}}
const STORE='asm70_live_stats_v1',ROSTER_STORE='asm70_live_roster_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let online={settings:null,players:[],games:[],callups:[]};
let localRoster=[];
let S=null,selectedPlayer=null,clockTimer=null,savePulse=0;
const actionDefs=[
  ['1M','✓ 1 punto','good'],['2M','✓ 2 punti','good'],['3M','✓ 3 punti','good'],
  ['1X','✕ TL','miss'],['2X','✕ 2 punti','miss'],['3X','✕ 3 punti','miss'],
  ['RD','Rimb. dif.','orange'],['RO','Rimb. off.','orange'],['AST','Assist','blue'],['STL','Recupero','blue'],['TO','Palla persa','red'],['BLK','Stoppata','blue'],
  ['FOUL','Fallo','red'],['FREC','Fallo subito','orange'],['SUB','Cambio','change']
];
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function fmt(sec){sec=Math.max(0,Math.round(sec||0));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.add('hidden'),1300)}
function save(){if(S)localStorage.setItem(STORE,JSON.stringify(S));}
function saveRoster(){localStorage.setItem(ROSTER_STORE,JSON.stringify(localRoster));}
function newState(players){let len=Number($('#periodLen').value)||600;return{version:1,createdAt:new Date().toISOString(),team:$('#teamInput').value.trim()||'ASM70 U14',opponent:$('#oppInput').value.trim()||'Avversari',homeAway:$('#homeAway').value,gameId:$('#gameSelect').value||null,periodLen:len,period:1,clock:len,running:false,oppScore:0,players:players.map((p,i)=>({id:p.id||uid(),name:p.name,num:Number(p.num)||0,onCourt:i<5,sec:0})),events:[]}}
function stat(pid,type,period=null){return S.events.filter(e=>e.playerId===pid&&e.type===type&&(period===null||e.period===period)).length}
function madePts(pid=null){return S.events.reduce((a,e)=>a+((pid===null||e.playerId===pid)?({'1M':1,'2M':2,'3M':3}[e.type]||0):0),0)}
function teamFouls(){return S.events.filter(e=>e.type==='FOUL'&&e.period===S.period).length}
function ratio(m,x){let a=stat(m,x+'M'),b=stat(m,x+'X');return a+'/'+(a+b)}
function findPlayer(id){return S.players.find(p=>p.id===id)}
async function loadOnline(){try{if(!db)await initDb();if(!db)throw Error('offline');let s=await db.from('team_settings').select('*').eq('id',1).single();if(s.data){online.settings=s.data;$('#teamInput').value=s.data.team_name||'ASM70 U14'}let [p,g,c]=await Promise.all([db.from('players').select('*').eq('active',true).order('display_order').order('jersey_number'),db.from('games').select('*').order('game_date',{ascending:false}).limit(40),db.from('game_callups').select('*')]);online.players=p.data||[];online.games=g.data||[];online.callups=c.data||[];$('#loadStatus').textContent='roster online caricato';}catch(e){$('#loadStatus').textContent='offline · uso roster locale'}mergeRoster();renderGameOptions();renderRosterSetup();}
function mergeRoster(){let saved=[];try{saved=JSON.parse(localStorage.getItem(ROSTER_STORE)||'[]')}catch(e){}let map=new Map();online.players.forEach(p=>map.set(String(p.id),{id:String(p.id),name:p.name,num:p.jersey_number||0,selected:true}));saved.forEach(p=>{if(!map.has(String(p.id)))map.set(String(p.id),p)});localRoster=[...map.values()].sort((a,b)=>(a.num||999)-(b.num||999)||a.name.localeCompare(b.name));}
function renderGameOptions(){let sel=$('#gameSelect'),cur=sel.value;sel.innerHTML='<option value="">Partita manuale</option>';online.games.forEach(g=>{let o=document.createElement('option');o.value=g.id;o.textContent=`${g.game_date} · ${g.home_away==='home'?'vs':'@'} ${g.opponent}`;sel.appendChild(o)});if([...sel.options].some(o=>o.value===cur))sel.value=cur;}
function renderRosterSetup(){let box=$('#rosterGrid');if(!localRoster.length){box.innerHTML='<div style="grid-column:1/-1;padding:18px;text-align:center;color:#7a8798">Nessun giocatore: aggiungilo qui sotto oppure dall’admin U14.</div>';return}box.innerHTML=localRoster.map((p,i)=>`<label class="rosterPick ${p.selected===false?'off':''}"><input type="checkbox" data-ridx="${i}" ${p.selected===false?'':'checked'}><span class="rnum">${esc(p.num)}</span><span class="rname">${esc(p.name)}</span></label>`).join('');$$('[data-ridx]').forEach(ch=>ch.onchange=()=>{localRoster[+ch.dataset.ridx].selected=ch.checked;saveRoster();renderRosterSetup()});}
$('#gameSelect').onchange=()=>{let id=$('#gameSelect').value,g=online.games.find(x=>x.id===id);if(!g)return;if(g.opponent)$('#oppInput').value=g.opponent;if(g.home_away)$('#homeAway').value=g.home_away;let ids=online.callups.filter(c=>c.game_id===id).map(c=>String(c.player_id));if(ids.length){localRoster.forEach(p=>p.selected=ids.includes(String(p.id)));saveRoster();renderRosterSetup();}};
$('#addPlayer').onclick=()=>{let num=Number($('#newNum').value),name=$('#newName').value.trim();if(!name)return toast('Inserisci il nome');localRoster.push({id:'local_'+uid(),name,num:num||0,selected:true});localRoster.sort((a,b)=>(a.num||999)-(b.num||999)||a.name.localeCompare(b.name));saveRoster();$('#newNum').value='';$('#newName').value='';renderRosterSetup();};
function showGame(){stopClock();$('#setupView').classList.add('hidden');$('#gameView').classList.remove('hidden');renderAll();}
function showSetup(){stopClock();save();$('#gameView').classList.add('hidden');$('#setupView').classList.remove('hidden');$('#resumeBtn').classList.toggle('hidden',!S);}
$('#startBtn').onclick=()=>{let chosen=localRoster.filter(p=>p.selected!==false);if(chosen.length<1)return toast('Seleziona almeno un giocatore');S=newState(chosen);save();showGame();};
$('#resumeBtn').onclick=()=>{if(S)showGame()};
$('#setupBack').onclick=showSetup;
$('#newGame').onclick=()=>{if(confirm('Vuoi chiudere questa partita e crearne una nuova?')){stopClock();localStorage.removeItem(STORE);S=null;showSetup();}};
function renderAll(){if(!S)return;$('#teamNameTop').textContent=S.team;$('#oppNameTop').textContent=S.opponent;$('#ourScore').textContent=madePts();$('#oppScore').textContent=S.oppScore||0;$('#periodBtn').textContent='Q'+S.period;$('#clock').textContent=fmt(S.clock);$('#clockBtn').textContent=S.running?'❚❚':'▶';$('#teamFouls').textContent=`Falli squadra Q${S.period}: ${teamFouls()}`;renderPlayers();renderEvents();renderStats();}
function renderPlayers(){let court=$('#courtPlayers'),bench=$('#benchPlayers');court.innerHTML='';bench.innerHTML='';let on=S.players.filter(p=>p.onCourt),off=S.players.filter(p=>!p.onCourt);function card(p,isCourt){let fouls=stat(p.id,'FOUL'),pts=madePts(p.id);return `<button class="player ${isCourt?'five':'out'} ${fouls>=5?'fouledout':''}" data-pid="${esc(p.id)}"><div><div class="num">${esc(p.num)}</div><div class="pname">${esc(p.name)}</div></div><div class="pmeta"><div class="ppts">${pts} pt</div><div class="fouls">${[0,1,2,3,4].map(i=>`<i class="${i<fouls?'on':''}"></i>`).join('')}</div></div></button>`}court.innerHTML=on.map(p=>card(p,true)).join('')||'<div class="empty" style="grid-column:1/-1">Nessun giocatore in campo.</div>';bench.innerHTML=off.map(p=>card(p,false)).join('')||'<div class="empty" style="padding:12px">Panchina vuota</div>';$$('[data-pid]').forEach(b=>b.onclick=()=>openActions(b.dataset.pid));}
function renderEvents(){let box=$('#eventList');if(!S.events.length){box.innerHTML='<div class="empty">Tocca il numero di un giocatore e registra la prima azione.</div>';return}let labels=Object.fromEntries(actionDefs.map(x=>[x[0],x[1]]));box.innerHTML=[...S.events].reverse().slice(0,120).map(e=>{let p=findPlayer(e.playerId),pt={'1M':1,'2M':2,'3M':3}[e.type]||'';return `<div class="event"><div class="etime">Q${e.period} ${fmt(e.clock)}</div><div class="enum">${p?esc(p.num):'—'}</div><div class="elabel">${p?esc(p.name)+' · ':''}${esc(labels[e.type]||e.label||e.type)}</div><div class="epoints">${pt?'+'+pt:''}</div></div>`}).join('');}
function renderStats(){if(!S)return;$('#statsScore').textContent=`${S.team} ${madePts()} – ${S.oppScore||0} ${S.opponent}`;$('#statsBody').innerHTML=S.players.map(p=>{let rd=stat(p.id,'RD'),ro=stat(p.id,'RO');return `<tr><td><div class="statsName"><span class="smallNum">${esc(p.num)}</span>${esc(p.name)}</div></td><td>${fmt(p.sec)}</td><td><b>${madePts(p.id)}</b></td><td>${ratio(p.id,'1')}</td><td>${ratio(p.id,'2')}</td><td>${ratio(p.id,'3')}</td><td>${rd}</td><td>${ro}</td><td><b>${rd+ro}</b></td><td>${stat(p.id,'AST')}</td><td>${stat(p.id,'STL')}</td><td>${stat(p.id,'TO')}</td><td>${stat(p.id,'BLK')}</td><td>${stat(p.id,'FOUL')}</td><td>${stat(p.id,'FREC')}</td></tr>`}).join('');}
function openActions(pid){selectedPlayer=pid;let p=findPlayer(pid);if(!p)return;$('#sheetNum').textContent=p.num;$('#sheetName').textContent=p.name;$('#sheetMini').textContent=`${madePts(pid)} punti · ${stat(pid,'FOUL')} falli · ${fmt(p.sec)} in campo`;$('#actions').innerHTML=actionDefs.map(a=>`<button class="act ${a[2]}" data-act="${a[0]}">${a[1]}</button>`).join('');$$('[data-act]').forEach(b=>b.onclick=()=>doAction(b.dataset.act));$('#actionBack').classList.remove('hidden');}
function closeActions(){$('#actionBack').classList.add('hidden')}
$('#closeSheet').onclick=closeActions;$('#actionBack').onclick=e=>{if(e.target===$('#actionBack'))closeActions()};
function doAction(type){if(type==='SUB'){closeActions();return openSubs()}let p=findPlayer(selectedPlayer);if(!p)return;S.events.push({id:uid(),playerId:p.id,type,period:S.period,clock:S.clock,at:new Date().toISOString()});save();closeActions();renderAll();toast(actionDefs.find(a=>a[0]===type)?.[1]||type);}
function openSubs(){let p=findPlayer(selectedPlayer);if(!p)return;let candidates=S.players.filter(x=>x.id!==p.id&&x.onCourt!==p.onCourt);$('#subTitle').textContent=p.onCourt?`Chi entra al posto di #${p.num} ${p.name}?`:`Chi esce per far entrare #${p.num} ${p.name}?`;$('#subGrid').innerHTML=candidates.length?candidates.map(x=>`<button class="subPick" data-sub="${esc(x.id)}">#${esc(x.num)} · ${esc(x.name)}</button>`).join(''):'<div class="empty" style="grid-column:1/-1">Nessun cambio disponibile.</div>';$$('[data-sub]').forEach(b=>b.onclick=()=>swapPlayers(p.id,b.dataset.sub));$('#subBack').classList.remove('hidden');}
function swapPlayers(a,b){let p=findPlayer(a),q=findPlayer(b);if(!p||!q)return;let x=p.onCourt;p.onCourt=q.onCourt;q.onCourt=x;S.events.push({id:uid(),playerId:p.id,otherPlayerId:q.id,type:'SUB',label:`Cambio ${p.onCourt?'entra':'esce'} con #${q.num} ${q.name}`,period:S.period,clock:S.clock,at:new Date().toISOString()});save();$('#subBack').classList.add('hidden');renderAll();toast('Cambio registrato');}
$('#closeSub').onclick=()=>$('#subBack').classList.add('hidden');$('#subBack').onclick=e=>{if(e.target===$('#subBack'))$('#subBack').classList.add('hidden')};
function stopClock(){if(clockTimer){clearInterval(clockTimer);clockTimer=null}if(S)S.running=false;}
function startClock(){if(!S||S.clock<=0)return;if(clockTimer)return;S.running=true;clockTimer=setInterval(()=>{if(!S||!S.running)return;S.clock=Math.max(0,S.clock-1);S.players.filter(p=>p.onCourt).forEach(p=>p.sec=(p.sec||0)+1);savePulse++;if(savePulse%5===0)save();if(S.clock===0){stopClock();save()}renderAll();},1000);renderAll();}
$('#clockBtn').onclick=()=>{if(!S)return;if(S.running){stopClock();save();renderAll()}else startClock()};
$('#periodBtn').onclick=()=>{if(!S)return;stopClock();let n=S.period>=4?1:S.period+1;if(confirm(`Passare a Q${n} e reimpostare il cronometro a ${fmt(S.periodLen)}?`)){S.period=n;S.clock=S.periodLen;save();renderAll()}};
$$('[data-opp]').forEach(b=>b.onclick=()=>{S.oppScore=(S.oppScore||0)+Number(b.dataset.opp);save();renderAll()});
$('#oppMinus').onclick=()=>{S.oppScore=Math.max(0,(S.oppScore||0)-1);save();renderAll()};
function undo(){if(!S||!S.events.length)return toast('Nulla da annullare');let e=S.events.pop();if(e.type==='SUB'&&e.otherPlayerId){let a=findPlayer(e.playerId),b=findPlayer(e.otherPlayerId);if(a&&b){let x=a.onCourt;a.onCourt=b.onCourt;b.onCourt=x}}toast('Ultima azione annullata');save();renderAll();}
$('#quickUndo').onclick=undo;
$('#clearEvents').onclick=()=>{if(confirm('Azzero tutte le azioni statistiche? Il punteggio ASM70 tornerà a 0.')){S.events=[];save();renderAll()}};
$$('.nav [data-tab]').forEach(b=>b.onclick=()=>{$$('.nav [data-tab]').forEach(x=>x.classList.toggle('on',x===b));$('#tabLive').classList.toggle('hidden',b.dataset.tab!=='live');$('#tabStats').classList.toggle('hidden',b.dataset.tab!=='stats');renderStats()});
$('#exportCsv').onclick=()=>{if(!S)return;let rows=[['Numero','Giocatore','Min','Punti','TL','2PT','3PT','RD','RO','RT','Assist','Recuperi','Perse','Stoppate','Falli','Falli subiti']];S.players.forEach(p=>{let rd=stat(p.id,'RD'),ro=stat(p.id,'RO');rows.push([p.num,p.name,fmt(p.sec),madePts(p.id),ratio(p.id,'1'),ratio(p.id,'2'),ratio(p.id,'3'),rd,ro,rd+ro,stat(p.id,'AST'),stat(p.id,'STL'),stat(p.id,'TO'),stat(p.id,'BLK'),stat(p.id,'FOUL'),stat(p.id,'FREC')])});let csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');let blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`stats_${S.opponent.replace(/[^a-z0-9]+/gi,'_')}_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.addEventListener('beforeunload',save);
(function init(){try{S=JSON.parse(localStorage.getItem(STORE)||'null')}catch(e){S=null}if(S)S.running=false;$('#resumeBtn').classList.toggle('hidden',!S);loadOnline();if(S){$('#teamInput').value=S.team||'ASM70 U14';$('#oppInput').value=S.opponent||'';$('#homeAway').value=S.homeAway||'home';$('#periodLen').value=String(S.periodLen||600)}})();
